### ISSUE TITLE
flutter sdk升级到最新版本后运行不起来

### ISSUE THREAD

**Issue by Charl0tter** [Kingtous/rustdesk_desktop_multi_window#8]
```yaml
dependencies:
  desktop_multi_window:
    git:
      url: https://github.com/Kingtous/rustdesk_desktop_multi_window
      ref: master
```

> `flutter` 版本
```
Flutter 3.8.0-1.0.pre.4 • channel master • https://github.com/flutter/flutter.git
Framework • revision a752c2f154 (2 days ago) • 2023-02-01 00:41:16 -0500
Engine • revision 1703a39662
Tools • Dart 3.0.0 (build 3.0.0-187.0.dev) • DevTools 2.20.1
```

执行 `flutter run -d windows -v` 后报错

```bash
[  +20 ms] Building Windows application... (completed in 9.9s)
[   +1 ms] Exception: Build process failed.
[   +4 ms] "flutter run" took 10,346ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:740:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1287:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by Kingtous** [comment]
flutter的问题，插件会跟随stable channel适配

**Comment by venyore** [comment]
要是能更新下readme就好了。。。很多东西要猜，比如：`desktop_lifecycle`都没人说要手动添加一下依赖？

**Comment by venyore** [comment]
> 要是能更新下readme就好了。。。很多东西要猜，比如：`desktop_lifecycle`都没人说要手动添加一下依赖？

原项目的问题，不需要手动去各个平台集成一下代码了，我删了也OK。不过与`windows_manager`还是有冲突？`Unhandled Exception: MissingPluginException(No implementation found for method ensureInitialized on channel window_manager)`

**Comment by bhlin790** [comment]
> 

在 3.7.5版本上也是一样的
